#!/bin/bash
targets=('*Trashes' '*TemporaryItems' '.Trash*' '$RECYCLE.BIN' 'System*Information' '._*')

if [ -z $1 ]
then
	echo "$0 directory-to-scan [-debug]"
	echo "Usage: removes some garbage elements."
	echo "If you pass '-debug' as 2nd parameter, it will echo what it will do."
	echo "Files removed:"
	echo "${targets[@]}"
else
	# Setting up the parameters for find
	for i in ${targets[@]}
	do
		# Handle first parameter differently than others
		if [ -z $first_done ]
		then
			args="-name $i"
			first_done=true
		else
			args=$args" -or -name $i"
		fi
	done

	# Actually, find the garbage
	if [ "$2" == "-debug" ]
	then
		echo "find $1 $args | xargs -0 rm -rvf"
	else
		find $1 $args -print0 | xargs -0 rm -rvf
	fi
fi
